export const drivers = [
    {
      team: "Mercedes",
      driverId: "HAM",
      driverName: "Lewis Hamilton",
      nationality: "British",
      carNumber: 44,
      points: 413,
      description: "Seven-time World Champion",
      isActive: true,
    },
    {
      team: "Mercedes",
      driverId: "RUS",
      driverName: "George Russell",
      nationality: "British",
      carNumber: 63,
      points: 275,
      description: "Rising star in Formula 1",
      isActive: true,
    },
    {
      team: "Red Bull",
      driverId: "VER",
      driverName: "Max Verstappen",
      nationality: "Dutch",
      carNumber: 1,
      points: 454,
      description: "Two-time World Champion",
      isActive: true,
    },
    {
      team: "Red Bull",
      driverId: "PER",
      driverName: "Sergio Perez",
      nationality: "Mexican",
      carNumber: 11,
      points: 305,
      description: "Experienced and consistent performer",
      isActive: true,
    },
    {
      team: "Ferrari",
      driverId: "LEC",
      driverName: "Charles Leclerc",
      nationality: "Monegasque",
      carNumber: 16,
      points: 340,
      description: "Young and talented driver",
      isActive: true,
    },
    {
      team: "Ferrari",
      driverId: "SAI",
      driverName: "Carlos Sainz",
      nationality: "Spanish",
      carNumber: 55,
      points: 302,
      description: "Skilled and strategic driver",
      isActive: true,
    },
    {
      team: "McLaren",
      driverId: "NOR",
      driverName: "Lando Norris",
      nationality: "British",
      carNumber: 4,
      points: 280,
      description: "Exciting young talent",
      isActive: true,
    },
    {
      team: "McLaren",
      driverId: "PIA",
      driverName: "Oscar Piastri",
      nationality: "Australian",
      carNumber: 81,
      points: 120,
      description: "Rookie with great potential",
      isActive: true,
    },
    {
      team: "Aston Martin",
      driverId: "ALO",
      driverName: "Fernando Alonso",
      nationality: "Spanish",
      carNumber: 14,
      points: 250,
      description: "Two-time World Champion",
      isActive: true,
    },
    {
      team: "Aston Martin",
      driverId: "STR",
      driverName: "Lance Stroll",
      nationality: "Canadian",
      carNumber: 18,
      points: 150,
      description: "Consistent and improving driver",
      isActive: true,
    },
    {
      team: "Alpine",
      driverId: "GAS",
      driverName: "Pierre Gasly",
      nationality: "French",
      carNumber: 10,
      points: 200,
      description: "Skilled and determined driver",
      isActive: true,
    },
    {
      team: "Alpine",
      driverId: "OCO",
      driverName: "Esteban Ocon",
      nationality: "French",
      carNumber: 31,
      points: 180,
      description: "Strong and competitive driver",
      isActive: true,
    },
    {
      team: "AlphaTauri",
      driverId: "TSU",
      driverName: "Yuki Tsunoda",
      nationality: "Japanese",
      carNumber: 22,
      points: 100,
      description: "Aggressive and fast driver",
      isActive: true,
    },
    {
      team: "AlphaTauri",
      driverId: "DEV",
      driverName: "Nyck de Vries",
      nationality: "Dutch",
      carNumber: 21,
      points: 50,
      description: "Rookie with potential",
      isActive: true,
    },
    {
      team: "Alfa Romeo",
      driverId: "BOT",
      driverName: "Valtteri Bottas",
      nationality: "Finnish",
      carNumber: 77,
      points: 220,
      description: "Experienced and reliable driver",
      isActive: true,
    },
    {
      team: "Alfa Romeo",
      driverId: "ZHO",
      driverName: "Zhou Guanyu",
      nationality: "Chinese",
      carNumber: 24,
      points: 90,
      description: "First Chinese F1 driver",
      isActive: true,
    },
    {
      team: "Haas",
      driverId: "MAG",
      driverName: "Kevin Magnussen",
      nationality: "Danish",
      carNumber: 20,
      points: 80,
      description: "Aggressive and determined driver",
      isActive: true,
    },
    {
      team: "Haas",
      driverId: "HUL",
      driverName: "Nico Hulkenberg",
      nationality: "German",
      carNumber: 27,
      points: 70,
      description: "Experienced and versatile driver",
      isActive: true,
    },
    {
      team: "Williams",
      driverId: "ALB",
      driverName: "Alexander Albon",
      nationality: "Thai",
      carNumber: 23,
      points: 60,
      description: "Skilled and improving driver",
      isActive: true,
    },
    {
      team: "Williams",
      driverId: "SAR",
      driverName: "Logan Sargeant",
      nationality: "American",
      carNumber: 2,
      points: 40,
      description: "Rookie with potential",
      isActive: true,
    },
//inactive drivers
    {
        team: "Retired",
        driverId: "VET",
        driverName: "Sebastian Vettel",
        nationality: "German",
        carNumber: 5,
        points: 0,
        description: "Four-time World Champion",
        isActive: false,
    },
    {
        team: "Retired",
        driverId: "RAI",
        driverName: "Kimi Räikkönen",
        nationality: "Finnish",
        carNumber: 7,
        points: 0,
        description: "2007 World Champion, known as 'The Iceman'",
        isActive: false,
    },
    {
        team: "Retired",
        driverId: "ALO",
        driverName: "Fernando Alonso",
        nationality: "Spanish",
        carNumber: 14,
        points: 0,
        description: "Two-time World Champion (currently active in other series)",
        isActive: false,
    },
    {
        team: "Retired",
        driverId: "ROS",
        driverName: "Nico Rosberg",
        nationality: "German",
        carNumber: 6,
        points: 0,
        description: "2016 World Champion, retired after winning the title",
        isActive: false,
    },
    {
        team: "Retired",
        driverId: "BUT",
        driverName: "Jenson Button",
        nationality: "British",
        carNumber: 22,
        points: 0,
        description: "2009 World Champion, now a pundit and ambassador",
        isActive: false,
    },
];